-- How many customers are there in each city of each state in the database
select haddr_state, haddr_city, count(customer_id) from customer
group by haddr_state, haddr_city with rollup;

-- Total revenue generated by each fare_mode on each day. 
select ride_date, fare_mode, rating_given_to_driver, sum(ride_fare) from rides
group by ride_date, fare_mode, rating_given_to_driver with rollup;

-- number of owned vehicles by vehicle_type and brand_name
select vehicle_type, brand_name, count(vehicle_id) from Vehicle where owned_or_rented='own'
group by vehicle_type, brand_name with rollup;

-- number of vehicle of each type, in each state.
select addr_state,vehicle_type, count(driver_id) from (driver INNER JOIN vehicle ON driver.vehicle_id = vehicle.vehicle_id)
group by addr_state, vehicle_type with rollup;